# Old File
lang-file: english.yml
signs:
    first-line-text: "ctw"
    first-line-text-replacement: "&4CaptureTheWool"
    on-invalid-room-replacement: "&4Invalid Room"
    on-invalid-map-replacement: "&4Invalid Map"
    on-disabled-map: "&4Disabled"
implement-spawn-cmd: true
ingame:
    allowed-commands:
        - spawn
        - tell
        - m
        - msg
        - t
        - whisper
        - w
        - helpop
        - report
        - salir
        - leave
        - jugar
        - entrar


#######################################
#                                     #
#            GAME CONFIG              #
#                                     #
#######################################

message-decorator: ""
user-fireworks-on-win: true
keep-teams-on-win: true
instakill-on-void: false
fall-damage: true

vip-armors:
   blue:
      R: 155
      G: 155
      B: 155
   red:
      R: 0 
      G: 0
      B: 0
      
sounds:
   win-wool-sound: VILLAGER_YES
   wool-pickup-sound: FIREWORK_LAUNCH 
   reversing-sound: ORB_PICKUP
   team-join-sound: LEVEL_UP
   join-command: CHEST_OPEN
   map-change: LEVEL_UP
   team-win-sound: WITHER_DEATH
   your-stats: ORB_PICKUP
   error: ENDERDRAGON_HIT
   
no-crafteable-items: "none" # "none", if you wan't desactivate this option, if you want add items, delete "none".
#    - WOOL
#    - ANVIL
    
no-protected-blocks: "none" # "none", if you wan't desactivate this option, if you want add items, delete "none".
#    - WEB
coins:
    kill: 5 
    capture: 10
